### ISSUE TITLE
Bug In Stormbreaker X9 

### ISSUE THREAD

**Issue by SmudgeShot** [stormbreaker-project/kernel_xiaomi_surya#6]
When i press home button it register as double click and open camera(a gesture in android11)and volume down need to be single tap everytime i decrease volume and long press to decrease do no register. Its not really a big problem to me because its easily avoidable but im just leaving it here. Phone is Poco X3 NFC Evolution X Rom Unofficial.

**Comment by Forenche** [comment]
Given a new build already, check if it still persists. Group link: https://t.me/joinchat/S4sChDqLL8VVITMX
Also please do mention the modules if you are using any, optmising apps like fde, l speed, etc when reporting an issue.
